# PROVENANCE: original | clean-room PDF domain engine per specs/PDF_DOMAIN_STACK.md
"""kairo.pdf — PDF domain with real extraction, redaction, forms, and signatures.

Re-exports the public API from ``kairo.pdf.engine``.
"""

from kairo.pdf.engine import (
    EngineUnavailableError,
    FormFillError,
    OCREngineUnavailableError,
    PDFEdit,
    PDFResult,
    RedactionError,
    SignatureError,
    WordBox,
    classify_pdf,
    extract_images,
    extract_text_with_coords,
    fill_form_fields,
    merge_pdfs,
    ocr_scanned_pdf,
    pdf_form_readback,
    pdf_pipeline,
    pdf_render_diff,
    pdf_signature_verify,
    pdf_text_roundtrip,
    read_form_fields,
    redact_text,
    render_page_hash,
    render_page_to_pixels,
    sign_pdf,
    split_pdf,
    tamper_pdf_byte,
    verify_signature,
)

__all__ = [
    "EngineUnavailableError",
    "FormFillError",
    "OCREngineUnavailableError",
    "PDFEdit",
    "PDFResult",
    "RedactionError",
    "SignatureError",
    "WordBox",
    "classify_pdf",
    "extract_images",
    "extract_text_with_coords",
    "fill_form_fields",
    "merge_pdfs",
    "ocr_scanned_pdf",
    "pdf_form_readback",
    "pdf_pipeline",
    "pdf_render_diff",
    "pdf_signature_verify",
    "pdf_text_roundtrip",
    "read_form_fields",
    "redact_text",
    "render_page_hash",
    "render_page_to_pixels",
    "sign_pdf",
    "split_pdf",
    "tamper_pdf_byte",
    "verify_signature",
]
