#!/usr/bin/env python3
# PROVENANCE: original | STATUS.md generator from domain plugin registry
"""Generate STATUS.md from the domain plugin registry.

Registered domains (via kairo.domains.registry) appear with their declared
status.  Prompt-only domains that are not yet registered are listed statically.

Usage:
    python scripts/gen_status.py              # write to STATUS.md
    python scripts/gen_status.py --output -   # print to stdout
    python scripts/gen_status.py --check      # exit 1 if STATUS.md is stale
"""

from __future__ import annotations

import argparse
import os
import sys

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

# ── Static domain entries (not registered in the plugin registry) ──────────
# (number, display_name, status, notes)
STATIC_PROMPT_ONLY: list[tuple[int, str, str]] = [
    (8, "Multimodal", "No oracle"),
    (9, "Media", "No oracle"),
    (11, "Cross-Platform", "No cross-platform E2E oracle"),
]

# Security is Real (wedge) but not a document-domain plugin
STATIC_REAL: list[tuple[int, str, str]] = [
    (
        12,
        "Security",
        "injection_block oracle — reference monitor + 15-case injection corpus, 0% attack-success",
    ),
    (
        15,
        "Anchor Perception",
        "grounding_accuracy + stable_id + token_reduction — local AX-tree + OCR + vision fusion, "
        "bbox-overlap dedup (UFO²), >=90% grounding on 120-screen corpus (incl. 20 canvas), "
        "stable IDs across frames, >=70% token reduction; live capture/OCR/vision = Experimental",
    ),
    (
        16,
        "CUA World Model + Verifier",
        "uistate_transition + verifier_agreement + loop_detection + no_receipt_without_verification — "
        "CUWM-style structural prediction, Universal Verifier (process+outcome rubric), "
        "stagnation/loop hard-stop, Ed25519 receipt gating (no receipt on verify-fail); "
        "live observe→act = Experimental",
    ),
]

# Map registry domain names to (number, display_name)
REGISTRY_DOMAIN_MAP: dict[str, tuple[int, str]] = {
    "word": (1, "Word (DOCX)"),
    "excel": (2, "Excel (XLSX)"),
    "powerpoint": (3, "PowerPoint (PPTX)"),
    "pdf": (4, "PDF"),
    "legal_redline": (5, "Legal Redline"),
    "design": (6, "Design (Canvas)"),
    "code": (7, "Code"),
    "notes": (10, "Research/notes"),
    "email": (14, "Email/comms"),
    "data_analytics": (13, "Data/analytics"),
    "webforms": (17, "Web-forms/apps"),
}


def _build_domain_rows() -> list[str]:
    """Build the domain status table rows from registry + static entries."""
    from kairo.domains.registry import discover

    domains = discover()
    domain_by_name = {d.name: d for d in domains}

    # Collect all entries: (number, display_name, status, notes)
    entries: list[tuple[int, str, str, str]] = []

    # Registered domains
    for name, (num, display) in REGISTRY_DOMAIN_MAP.items():
        d = domain_by_name.get(name)
        if d:
            entries.append((num, display, f"**{d.status}**", d.summary))

    # Static prompt-only domains
    for num, display, notes in STATIC_PROMPT_ONLY:
        entries.append((num, display, "prompt-only / not shipped", notes))

    # Static Real domains (Security)
    for num, display, notes in STATIC_REAL:
        entries.append((num, display, "**Real (wedge)**", notes))

    # Sort by domain number
    entries.sort(key=lambda e: e[0])

    rows = ["| # | Domain | Status | Notes |", "|---|---|---|---|"]
    for num, display, status, notes in entries:
        rows.append(f"| {num} | {display} | {status} | {notes} |")
    return rows


def generate_status_md() -> str:
    """Generate the full STATUS.md content."""
    domain_rows = _build_domain_rows()

    lines = [
        "# Kairo Phantom — Status",
        "",
        "> Honest status labels per specs/DEFINITION_OF_DONE.md §9 and specs/CLAIM_DISCIPLINE.md.",
        "> A domain is \"Real\" only when its practitioner-grade oracle passes on real fixtures.",
        "> Shipping a mislabelled domain is a release blocker.",
        "> ",
        "> **This file is GENERATED by `scripts/gen_status.py` — do not hand-edit.**",
        "> Domain status comes from each domain's descriptor in `kairo/domains/<name>/__init__.py`.",
        "",
        "## Wedge Status",
        "",
        "| Wedge | Status | Oracle | Evidence |",
        "|---|---|---|---|",
        "| **Legal-redline** | **Real (wedge)** | docx_tracked_changes_readback + clause_coverage + no_hallucinated_citation + injection_block + airgap_egress + audit_log_integrity | [Wedge Acceptance Audit](docs/acceptance/README.md) — 14 scenarios, all green, zero skips |",
        "",
        "## Domain Status",
        "",
    ]
    lines.extend(domain_rows)
    lines.extend([
        "",
        "## Trust Infrastructure",
        "",
        "| Component | Status | Oracle | Notes |",
        "|---|---|---|---|",
        "| Ed25519 Audit Log | Real (wedge) | audit_chain | Hash-chained, Ed25519-signed, verify_chain passes |",
        "| Zero-Egress Report | Real (wedge) | signed report | Ed25519-signed, verifiable |",
        "| Air-Gap Seal (R3) | Real (wedge) | airgap_egress | Sealed mode, 0 outbound, kill-proven |",
        "| Injection Defense (R5) | Real (wedge) | injection_block | Reference monitor, 0% attack-success, kill-proven |",
        "| Sealed Build Profile | Real (wedge) | sealed_no_network | Static scan + runtime oracle, no network symbols |",
        "| CLI | Real (wedge) | test_cli_redline | redline + verify commands, tamper kill-proofs |",
        "",
        "## Claim Discipline",
        "",
        "- ✅ \"Legal-redline wedge: production-ready (offline, cited, injection-safe, signed, air-gapped)\"",
        "- ❌ NOT \"the 12-domain product is ready\" — all other domains are prompt-only / not shipped",
        "- ❌ NOT \"cryptographic proof no bytes ever leave\" — we say \"reproducible, signed report showing zero outbound connections\"",
    ])
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate STATUS.md from the domain registry")
    parser.add_argument("--output", default="STATUS.md", help="Output path (default: STATUS.md; '-' for stdout)")
    parser.add_argument("--check", action="store_true", help="Exit 1 if STATUS.md is stale")
    args = parser.parse_args()

    content = generate_status_md()

    if args.check:
        status_path = os.path.join(_REPO_ROOT, "STATUS.md")
        if not os.path.exists(status_path):
            print("::error::STATUS.md not found", file=sys.stderr)
            return 1
        with open(status_path, encoding="utf-8") as f:
            existing = f.read()
        if existing != content:
            print("::error::STATUS.md is stale — run 'python scripts/gen_status.py' to regenerate", file=sys.stderr)
            return 1
        print("✅ STATUS.md is up to date")
        return 0

    if args.output == "-":
        print(content, end="")
    else:
        out_path = args.output if os.path.isabs(args.output) else os.path.join(_REPO_ROOT, args.output)
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"Generated {out_path}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
